"""Add editor_html column to Lesson model

Revision ID: 985f04df7784
Revises: 4b4f89a747f1
Create Date: 2025-06-23 12:57:32.289735

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '985f04df7784'
down_revision = '4b4f89a747f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lesson', schema=None) as batch_op:
        batch_op.add_column(sa.Column('editor_html', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lesson', schema=None) as batch_op:
        batch_op.drop_column('editor_html')

    # ### end Alembic commands ###
